export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';

export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

