export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';

export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';

export const FETCH_TRACK_HISTORY_SUCCESS = 'FETCH_TRACK_HISTORY_SUCCESS';

export const FETCH_ARTIST_BY_ID_SUCCESS = 'FETCH_ARTIST_BY_ID_SUCCESS';

export const FETCH_ALBUM_BY_ID_SUCCESS = 'FETCH_ALBUM_BY_ID_SUCCESS';

export const FETCH_TRACK_BY_ID_SUCCESS = 'FETCH_TRACK_BY_ID_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';


